
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Punto_de_venta.Bases_de_datos
{

using System;
    using System.Collections.Generic;
    
public partial class Estante
{

    public Estante()
    {

        this.Producto = new HashSet<Producto>();

    }


    public int IdEstante { get; set; }

    public string NombreEstante { get; set; }

    public string DescripciónEstante { get; set; }



    public virtual ICollection<Producto> Producto { get; set; }

}

}
