
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Punto_de_venta.Bases_de_datos
{

using System;
    using System.Collections.Generic;
    
public partial class Modulos
{

    public Modulos()
    {

        this.PerfilModulo = new HashSet<PerfilModulo>();

        this.Perfiles = new HashSet<Perfiles>();

    }


    public short IdModulos { get; set; }

    public string DescripcionModulo { get; set; }

    public bool EstadoModulo { get; set; }

    public short FKModuloPrincipal { get; set; }



    public virtual ModuloPrincipal ModuloPrincipal { get; set; }

    public virtual ICollection<PerfilModulo> PerfilModulo { get; set; }

    public virtual ICollection<Perfiles> Perfiles { get; set; }

}

}
