
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Punto_de_venta.Bases_de_datos
{

using System;
    using System.Collections.Generic;
    
public partial class ModuloPrincipal
{

    public ModuloPrincipal()
    {

        this.Modulos = new HashSet<Modulos>();

    }


    public short IdModuloPrincipal { get; set; }

    public string DescripcionModuloPrin { get; set; }

    public bool EstadoModuloPrin { get; set; }



    public virtual ICollection<Modulos> Modulos { get; set; }

}

}
