
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Punto_de_venta.Bases_de_datos
{

using System;
    using System.Collections.Generic;
    
public partial class Perfiles
{

    public Perfiles()
    {

        this.PerfilModulo = new HashSet<PerfilModulo>();

        this.Usuario = new HashSet<Usuario>();

        this.Modulos = new HashSet<Modulos>();

    }


    public short IdPerfil { get; set; }

    public string DescripcionPerfil { get; set; }

    public bool EstadoPerfil { get; set; }



    public virtual ICollection<PerfilModulo> PerfilModulo { get; set; }

    public virtual ICollection<Usuario> Usuario { get; set; }

    public virtual ICollection<Modulos> Modulos { get; set; }

}

}
