
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Punto_de_venta.Bases_de_datos
{

using System;
    using System.Collections.Generic;
    
public partial class PerfilModulo
{

    public short FKPerfilId { get; set; }

    public short FKModuloId { get; set; }

    public long IdPerfilModulo { get; set; }



    public virtual Modulos Modulos { get; set; }

    public virtual Perfiles Perfiles { get; set; }

}

}
