
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Punto_de_venta.Bases_de_datos
{

using System;
    using System.Collections.Generic;
    
public partial class Producto
{

    public Producto()
    {

        this.Compra = new HashSet<Compra>();

        this.DetalleVentas = new HashSet<DetalleVentas>();

    }


    public string IdProducto { get; set; }

    public string Nombre { get; set; }

    public int Cantidad { get; set; }

    public decimal PrecioVenta { get; set; }

    public decimal PrecioCosto { get; set; }

    public int Categoria { get; set; }

    public int Proveedor { get; set; }

    public Nullable<int> Estante { get; set; }

    public string Tipo_Impuesto { get; set; }



    public virtual ICollection<Compra> Compra { get; set; }

    public virtual Categoria Categoria1 { get; set; }

    public virtual Estante Estante1 { get; set; }

    public virtual Proveedor Proveedor1 { get; set; }

    public virtual ICollection<DetalleVentas> DetalleVentas { get; set; }

}

}
