
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Punto_de_venta.Bases_de_datos
{

using System;
    using System.Collections.Generic;
    
public partial class Usuario
{

    public Usuario()
    {

        this.Estado1 = new HashSet<Estado>();

    }


    public short IdUsuario { get; set; }

    public string Usr { get; set; }

    public string Pwd { get; set; }

    public string Identidad { get; set; }

    public string PrimerNombre { get; set; }

    public string SegundoNombre { get; set; }

    public string PrimerApellido { get; set; }

    public string SegundoApellido { get; set; }

    public bool Estado { get; set; }

    public short FKPerfil { get; set; }

    public string Contacto { get; set; }

    public string ContactoFamiliar { get; set; }



    public virtual Perfiles Perfiles { get; set; }

    public virtual ICollection<Estado> Estado1 { get; set; }

}

}
