
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Punto_de_venta.Bases_de_datos
{

using System;
    using System.Collections.Generic;
    
public partial class Venta
{

    public Venta()
    {

        this.DetalleVentas = new HashSet<DetalleVentas>();

    }


    public int IdVenta { get; set; }

    public System.DateTime Fecha_Venta { get; set; }

    public decimal Total_Venta { get; set; }

    public Nullable<int> Estado { get; set; }

    public Nullable<decimal> Impuesto_Gravado_15_ { get; set; }

    public Nullable<decimal> Impuesto_Gravado_18_ { get; set; }

    public Nullable<decimal> ISV15_ { get; set; }

    public Nullable<decimal> ISV18_ { get; set; }

    public Nullable<decimal> Importe_Exento { get; set; }

    public Nullable<decimal> Importe_Exonerado { get; set; }



    public virtual ICollection<DetalleVentas> DetalleVentas { get; set; }

    public virtual Estado Estado1 { get; set; }

}

}
