
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Punto_de_venta.Bases_de_datos
{

using System;
    using System.Collections.Generic;
    
public partial class Vista1
{

    public string Codigo { get; set; }

    public string Producto { get; set; }

    public int Existencias { get; set; }

    public decimal Precio { get; set; }

    public decimal Costo { get; set; }

    public string Categoria { get; set; }

    public string Proveedor { get; set; }

}

}
